# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = 'f19'
  config.vm.box_url = 'http://www.krishnaraman.net/downloads/fedora-19.box'
  config.vm.forward_port 80, 8080
  config.vm.forward_port 443, 8443
  config.vm.forward_port 53, 53
  config.vm.host_name = 'broker.example.com'
  
  config.vm.share_folder "manifests", "/home/vagrant/manifests", "manifests"
  config.vm.provision :shell, :inline => %{ \
    touch /var/log/origin-setup.log; \
    sudo /bin/puppet apply --verbose /home/vagrant/manifests/init.pp      | tee -a /var/log/origin-setup.log; \
    sudo /bin/systemctl restart  network.service                          | tee -a /var/log/origin-setup.log; \
    sudo /bin/puppet module uninstall openshift/openshift_origin          | tee -a /var/log/origin-setup.log; \
    sudo /bin/puppet module install openshift/openshift_origin            | tee -a /var/log/origin-setup.log; \
    sudo /bin/puppet apply --verbose /home/vagrant/manifests/configure.pp | tee -a /var/log/origin-setup.log; \
    sudo /bin/systemctl restart  activemq.service                  | tee -a /var/log/origin-setup.log; \
    sudo /bin/systemctl restart  cgconfig.service                  | tee -a /var/log/origin-setup.log; \
    sudo /bin/systemctl restart  cgred.service                     | tee -a /var/log/origin-setup.log; \
    sudo /bin/systemctl restart  openshift-tc.service              | tee -a /var/log/origin-setup.log; \
    sleep 5; \
    sudo /bin/systemctl restart  httpd.service                     | tee -a /var/log/origin-setup.log; \
    sudo /bin/systemctl restart  openshift-broker.service          | tee -a /var/log/origin-setup.log; \
    sudo /bin/systemctl restart  openshift-node-web-proxy.service  | tee -a /var/log/origin-setup.log; \
    sudo /bin/systemctl restart  named.service                     | tee -a /var/log/origin-setup.log; \
    sudo /bin/systemctl restart  mcollective.service               | tee -a /var/log/origin-setup.log; \
    sudo /usr/sbin/oo-register-dns -h broker -n 127.0.0.1          | tee -a /var/log/origin-setup.log; \
    sudo /etc/cron.minutely/openshift-facts; \
  }
end
