name 'openshift-openshift_origin'
version '0.1.14'

author 'Mojo Lingo, Red Hat'
license 'ASL'
project_page 'https://github.com/kraman/puppet-openshift_origin'
source 'git://github.com/openshift/puppet-openshift_origin.git'
summary 'Module for installing Red Hat Openshift'
description 'Configures OpenShift Origin broker, nodes and support servers'
dependency 'puppetlabs/ntp', '>=0.1.0'
dependency 'puppetlabs/stdlib', '>=2.6.0'
