name 'openshift-openshift_origin'
version '0.1.1'
source 'git://github.com/openshift/puppet-openshift_origin.git'
author 'Mojo Lingo, Red Hat'
license 'ASL'
summary 'Module for installing Red Hat Openshift'
description 'Configures OpenShift Origin broker, nodes and support servers'
project_page 'https://github.com/kraman/puppet-openshift_origin'
dependency 'puppetlabs/ntp', '>= 0.1.0'
dependency 'puppetlabs/stdlib', '>= 0.1.0'
